# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 09:14
from __future__ import unicode_literals

import activflow.tests.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name=b'Last Updated')),
                ('grault', models.CharField(max_length=50, verbose_name=b'Grault')),
                ('thud', models.IntegerField(verbose_name=b'Thud')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name=b'Last Updated')),
                ('subject', models.CharField(max_length=70, verbose_name=b'Subject')),
                ('bar', models.CharField(max_length=200, validators=[activflow.tests.validators.validate_initial_cap], verbose_name=b'Bar')),
                ('baz', models.CharField(choices=[(b'CR', b'Corge'), (b'WL', b'Waldo')], max_length=30, verbose_name=b'Baz')),
                ('qux', models.TextField(blank=True, verbose_name=b'Qux')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
