# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:15
from __future__ import unicode_literals

import activflow.tests.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('grault', models.CharField(max_length=50, verbose_name='Grault')),
                ('thud', models.IntegerField(verbose_name='Thud')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('subject', models.CharField(max_length=70, verbose_name='Subject')),
                ('bar', models.CharField(max_length=200, validators=[activflow.tests.validators.validate_initial_cap], verbose_name='Bar')),
                ('baz', models.CharField(choices=[('CR', 'Corge'), ('WL', 'Waldo')], max_length=30, verbose_name='Baz')),
                ('qux', models.TextField(blank=True, verbose_name='Qux')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
