# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_foolineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corge',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
        ),
        migrations.AlterField(
            model_name='foo',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
        ),
    ]
