# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangoflow.core.mixins
import djangoflow.tests.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name=b'Last Updated')),
                ('bar', models.CharField(max_length=200, validators=[djangoflow.tests.validators.validate_initial_cap], verbose_name=b'Bar')),
                ('baz', models.CharField(choices=[(b'CR', b'Corge'), (b'WL', b'Waldo')], max_length=30, verbose_name=b'Baz')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, djangoflow.core.mixins.BaseEntityMixin),
        ),
        migrations.CreateModel(
            name='SecondActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name=b'Last Updated')),
                ('qux', models.TextField(blank=True, verbose_name=b'Qux')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, djangoflow.core.mixins.BaseEntityMixin),
        ),
    ]
