language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1
  - DJANGO_VERSION=3.2

# command to install dependencies
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coveralls

# command to run tests
script:
  - coverage run --source='.' --omit='demo.py,*wsgi.py' manage.py test activflow.tests

after_success:
  - coveralls
