version: '3.5'

services:
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      activflow-net:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=staging
    command: sh ./scripts/on-container-start.sh
    hostname: activflow
    expose:
      - "8000"
    volumes:
      - ./:/app
      - static:/app/activflow/static
    networks:
      activflow-net:
    depends_on:
      - db
  web:
    image: nginx:latest
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/static
    networks:
      activflow-net:
    depends_on:
      - app

volumes:
  static:

networks:
  activflow-net:
