# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='module_ref',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
