# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flow_ref_key',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
