# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20160306_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='role',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
