# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160312_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[(b'Initiated', b'Initiated'), (b'Withdrawn', b'Withdrawn'), (b'Completed', b'Completed')], max_length=30, verbose_name=b'Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'Not Started', b'Not Started'), (b'In Progress', b'In Progress'), (b'Rolled Back', b'Rolled Back'), (b'Completed', b'Completed')], max_length=30, verbose_name=b'Status'),
        ),
    ]
